---
- name: "install | Install PostgreSQL {{ pg_version }} + psycopg2"
  ansible.builtin.apt:
    name:
      - "postgresql-{{ pg_version }}"
      - "postgresql-contrib"
      - "python3-psycopg2"   # required by community.postgresql modules
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: "install | Ensure PostgreSQL is enabled + running"
  ansible.builtin.systemd_service:
    name: "postgresql@{{ pg_version }}-main"
    enabled: true
    state: started
