---
- name: "install | Install redis-server"
  ansible.builtin.apt:
    name: redis-server
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: "install | Ensure redis is enabled"
  ansible.builtin.systemd_service:
    name: redis-server
    enabled: true
