# Managed by Ansible (roles/pkgcache). devpi = caching PyPI mirror, pinned.
FROM {{ pkgcache_python_image }}
RUN pip install --no-cache-dir devpi-server=={{ pkgcache_devpi_server_version }} devpi-web=={{ pkgcache_devpi_web_version }} \
 && useradd --uid {{ pkgcache_devpi_uid }} --user-group --no-create-home --shell /usr/sbin/nologin devpi
USER {{ pkgcache_devpi_uid }}
EXPOSE 3141
ENTRYPOINT ["devpi-server"]
