---
- name: "Service | Reconfigure CrowdSec so the daemon reloads url + key"
  by_systems.opnsense.opnsense_crowdsec_service:
    host: "{{ crowdsec_fw_bouncer_api.host }}"
    key: "{{ crowdsec_fw_bouncer_api.key }}"
    secret: "{{ crowdsec_fw_bouncer_api.secret }}"
    verify_ssl: false
    state: reconfigured
  when: crowdsec_fw_bouncer_dirty | default(true) | bool
