---
all:
  children:

    proxmox_nodes:
      hosts:
        srv-proxmox-poc-01:
          ansible_host: 10.6.224.105
          ansible_port: 22222
          ansible_user: by-systems
          ansible_become: true

    opnsense:
      hosts:
        vm-opnsense-01:
          ansible_host: 10.6.224.106   # WAN IP — reachable via static route from Rune VM
          ansible_connection: ssh
          ansible_user: root
          ansible_port: 22
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_rune_automation
          ansible_python_interpreter: /usr/local/bin/python3  # FreeBSD path

    vms:
      hosts:
        vm-debian-bootstrap-test-01:
          ansible_host: 10.6.225.11
          ansible_port: 22222
          ansible_user: by-systems
          ansible_become: true
