---
all:
  children:

    proxmox_nodes:
      hosts:
        srv-proxmox-poc-01:
          ansible_host: 10.6.224.105
          ansible_port: 22222
          ansible_user: by-systems
          ansible_become: true

    vms:
      hosts:
        vm-debian-bootstrap-test-01:
          ansible_host: 10.6.225.11
          ansible_port: 22222
          ansible_user: by-systems
          ansible_become: true
